/********************************************************************************
** Form generated from reading ui file 'brainstorm.jui'
**
** Created: Tue Apr 5 15:10:00 2011
**      by: Qt User Interface Compiler version 4.5.2
**
** WARNING! All changes made in this file will be lost when recompiling ui file!
********************************************************************************/

package brainstorm;

import com.trolltech.qt.core.*;
import com.trolltech.qt.gui.*;

public class Ui_MainWindow implements com.trolltech.qt.QUiForm<QMainWindow>
{
    public QAction actionQuit;
    public QAction actionNew_Note;
    public QAction actionRename_Note;
    public QAction actionDelete_Note;
    public QAction actionNew_Category;
    public QAction actionRename_Category;
    public QAction actionDelete_Category;
    public QAction actionImport_Category;
    public QAction actionExport_Category;
    public QAction actionUndo;
    public QAction actionRedo;
    public QAction actionCut;
    public QAction actionCopy;
    public QAction actionPaste;
    public QAction actionAbout_Brainstorm;
    public QAction actionAbout_QtJambi;
    public QAction actionBold;
    public QAction actionItalic;
    public QAction actionUnderline;
    public QAction actionStrikethrough;
    public QAction actionLeft;
    public QAction actionCenter;
    public QAction actionRight;
    public QAction actionFull;
    public QAction actionShow_Fonts;
    public QAction actionShow_Colors;
    public QAction actionIncrease_Font;
    public QAction actionDecrease_Font;
    public QAction actionReset_Font;
    public QAction actionPrint_Note;
    public QAction actionIncrease_Indent;
    public QAction actionDecrease_Indent;
    public QAction actionBullet_List;
    public QAction actionNumeric_List;
    public QAction actionNext_Note;
    public QAction actionPrevious_Note;
    public QAction actionNext_Category;
    public QAction actionPrevious_Category;
    public QAction actionSave_Note;
    public QWidget centralwidget;
    public QHBoxLayout horizontalLayout;
    public QSplitter splitterNotes;
    public QSplitter splitterCategories;
    public QListView listCategories;
    public QListView listNotes;
    public QTextEdit textNote;
    public QFontComboBox comboFonts;
    public QComboBox comboFontSizes;
    public QComboBox comboFontColors;
    public QMenuBar menubar;
    public QMenu menuFile;
    public QMenu menuEdit;
    public QMenu menuFormat;
    public QMenu menuJustify;
    public QMenu menuList_Style;
    public QMenu menuHelp;
    public QMenu menuView;
    public QToolBar toolBar;

    public Ui_MainWindow() { super(); }

    public void setupUi(QMainWindow MainWindow)
    {
        MainWindow.setObjectName("MainWindow");
        MainWindow.resize(new QSize(682, 388).expandedTo(MainWindow.minimumSizeHint()));
        MainWindow.setWindowIcon(new QIcon(new QPixmap("../resources/brainstorm.png")));
        actionQuit = new QAction(MainWindow);
        actionQuit.setObjectName("actionQuit");
        actionQuit.setMenuRole(com.trolltech.qt.gui.QAction.MenuRole.QuitRole);
        actionNew_Note = new QAction(MainWindow);
        actionNew_Note.setObjectName("actionNew_Note");
        actionNew_Note.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/textedit/mac/filenew.png")));
        actionRename_Note = new QAction(MainWindow);
        actionRename_Note.setObjectName("actionRename_Note");
        actionDelete_Note = new QAction(MainWindow);
        actionDelete_Note.setObjectName("actionDelete_Note");
        actionNew_Category = new QAction(MainWindow);
        actionNew_Category.setObjectName("actionNew_Category");
        actionNew_Category.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/tools/designer/folder.png")));
        actionRename_Category = new QAction(MainWindow);
        actionRename_Category.setObjectName("actionRename_Category");
        actionDelete_Category = new QAction(MainWindow);
        actionDelete_Category.setObjectName("actionDelete_Category");
        actionImport_Category = new QAction(MainWindow);
        actionImport_Category.setObjectName("actionImport_Category");
        actionExport_Category = new QAction(MainWindow);
        actionExport_Category.setObjectName("actionExport_Category");
        actionUndo = new QAction(MainWindow);
        actionUndo.setObjectName("actionUndo");
        actionUndo.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/textedit/mac/editundo.png")));
        actionRedo = new QAction(MainWindow);
        actionRedo.setObjectName("actionRedo");
        actionRedo.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/textedit/mac/editredo.png")));
        actionCut = new QAction(MainWindow);
        actionCut.setObjectName("actionCut");
        actionCut.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/textedit/mac/editcut.png")));
        actionCopy = new QAction(MainWindow);
        actionCopy.setObjectName("actionCopy");
        actionCopy.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/textedit/mac/editcopy.png")));
        actionPaste = new QAction(MainWindow);
        actionPaste.setObjectName("actionPaste");
        actionPaste.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/textedit/mac/editpaste.png")));
        actionAbout_Brainstorm = new QAction(MainWindow);
        actionAbout_Brainstorm.setObjectName("actionAbout_Brainstorm");
        actionAbout_Brainstorm.setIcon(new QIcon(new QPixmap("../resources/brainstorm.png")));
        actionAbout_QtJambi = new QAction(MainWindow);
        actionAbout_QtJambi.setObjectName("actionAbout_QtJambi");
        actionAbout_QtJambi.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/qtlogo-64.png")));
        actionBold = new QAction(MainWindow);
        actionBold.setObjectName("actionBold");
        actionBold.setCheckable(true);
        actionItalic = new QAction(MainWindow);
        actionItalic.setObjectName("actionItalic");
        actionItalic.setCheckable(true);
        actionUnderline = new QAction(MainWindow);
        actionUnderline.setObjectName("actionUnderline");
        actionUnderline.setCheckable(true);
        actionStrikethrough = new QAction(MainWindow);
        actionStrikethrough.setObjectName("actionStrikethrough");
        actionStrikethrough.setCheckable(true);
        actionLeft = new QAction(MainWindow);
        actionLeft.setObjectName("actionLeft");
        actionLeft.setCheckable(true);
        actionLeft.setChecked(true);
        actionLeft.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/textedit/mac/textleft.png")));
        actionCenter = new QAction(MainWindow);
        actionCenter.setObjectName("actionCenter");
        actionCenter.setCheckable(true);
        actionCenter.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/textedit/mac/textcenter.png")));
        actionRight = new QAction(MainWindow);
        actionRight.setObjectName("actionRight");
        actionRight.setCheckable(true);
        actionRight.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/textedit/mac/textright.png")));
        actionFull = new QAction(MainWindow);
        actionFull.setObjectName("actionFull");
        actionFull.setCheckable(true);
        actionFull.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/textedit/mac/textjustify.png")));
        actionShow_Fonts = new QAction(MainWindow);
        actionShow_Fonts.setObjectName("actionShow_Fonts");
        actionShow_Colors = new QAction(MainWindow);
        actionShow_Colors.setObjectName("actionShow_Colors");
        actionIncrease_Font = new QAction(MainWindow);
        actionIncrease_Font.setObjectName("actionIncrease_Font");
        actionIncrease_Font.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/demos/imageviewer/zoomin.png")));
        actionDecrease_Font = new QAction(MainWindow);
        actionDecrease_Font.setObjectName("actionDecrease_Font");
        actionDecrease_Font.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/demos/imageviewer/zoomout.png")));
        actionReset_Font = new QAction(MainWindow);
        actionReset_Font.setObjectName("actionReset_Font");
        actionPrint_Note = new QAction(MainWindow);
        actionPrint_Note.setObjectName("actionPrint_Note");
        actionPrint_Note.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/fileprint.png")));
        actionIncrease_Indent = new QAction(MainWindow);
        actionIncrease_Indent.setObjectName("actionIncrease_Indent");
        actionDecrease_Indent = new QAction(MainWindow);
        actionDecrease_Indent.setObjectName("actionDecrease_Indent");
        actionBullet_List = new QAction(MainWindow);
        actionBullet_List.setObjectName("actionBullet_List");
        actionBullet_List.setCheckable(true);
        actionNumeric_List = new QAction(MainWindow);
        actionNumeric_List.setObjectName("actionNumeric_List");
        actionNumeric_List.setCheckable(true);
        actionNext_Note = new QAction(MainWindow);
        actionNext_Note.setObjectName("actionNext_Note");
        actionPrevious_Note = new QAction(MainWindow);
        actionPrevious_Note.setObjectName("actionPrevious_Note");
        actionNext_Category = new QAction(MainWindow);
        actionNext_Category.setObjectName("actionNext_Category");
        actionPrevious_Category = new QAction(MainWindow);
        actionPrevious_Category.setObjectName("actionPrevious_Category");
        actionSave_Note = new QAction(MainWindow);
        actionSave_Note.setObjectName("actionSave_Note");
        actionSave_Note.setIcon(new QIcon(new QPixmap("classpath:com/trolltech/images/save.png")));
        centralwidget = new QWidget(MainWindow);
        centralwidget.setObjectName("centralwidget");
        horizontalLayout = new QHBoxLayout(centralwidget);
        horizontalLayout.setSpacing(3);
        horizontalLayout.setMargin(3);
        horizontalLayout.setObjectName("horizontalLayout");
        splitterNotes = new QSplitter(centralwidget);
        splitterNotes.setObjectName("splitterNotes");
        splitterNotes.setOrientation(com.trolltech.qt.core.Qt.Orientation.Horizontal);
        splitterCategories = new QSplitter(splitterNotes);
        splitterCategories.setObjectName("splitterCategories");
        splitterCategories.setOrientation(com.trolltech.qt.core.Qt.Orientation.Vertical);
        listCategories = new QListView(splitterCategories);
        listCategories.setObjectName("listCategories");
        splitterCategories.addWidget(listCategories);
        listNotes = new QListView(splitterCategories);
        listNotes.setObjectName("listNotes");
        splitterCategories.addWidget(listNotes);
        splitterNotes.addWidget(splitterCategories);
        textNote = new QTextEdit(splitterNotes);
        textNote.setObjectName("textNote");
        QFont font = new QFont();
        font.setFamily("Calibri");
        font.setPointSize(11);
        textNote.setFont(font);
        textNote.setTextInteractionFlags(com.trolltech.qt.core.Qt.TextInteractionFlag.createQFlags(com.trolltech.qt.core.Qt.TextInteractionFlag.LinksAccessibleByMouse,com.trolltech.qt.core.Qt.TextInteractionFlag.TextEditable,com.trolltech.qt.core.Qt.TextInteractionFlag.TextEditorInteraction,com.trolltech.qt.core.Qt.TextInteractionFlag.TextSelectableByKeyboard,com.trolltech.qt.core.Qt.TextInteractionFlag.TextSelectableByMouse));
        splitterNotes.addWidget(textNote);

        horizontalLayout.addWidget(splitterNotes);

        comboFonts = new QFontComboBox(centralwidget);
        comboFonts.setObjectName("comboFonts");
        QSizePolicy sizePolicy = new QSizePolicy(com.trolltech.qt.gui.QSizePolicy.Policy.Fixed, com.trolltech.qt.gui.QSizePolicy.Policy.Fixed);
        sizePolicy.setHorizontalStretch((byte)0);
        sizePolicy.setVerticalStretch((byte)0);
        sizePolicy.setHeightForWidth(comboFonts.sizePolicy().hasHeightForWidth());
        comboFonts.setSizePolicy(sizePolicy);
        comboFonts.setMaximumSize(new QSize(120, 16777215));

        horizontalLayout.addWidget(comboFonts);

        comboFontSizes = new QComboBox(centralwidget);
        comboFontSizes.setObjectName("comboFontSizes");
        QSizePolicy sizePolicy1 = new QSizePolicy(com.trolltech.qt.gui.QSizePolicy.Policy.Fixed, com.trolltech.qt.gui.QSizePolicy.Policy.Fixed);
        sizePolicy1.setHorizontalStretch((byte)0);
        sizePolicy1.setVerticalStretch((byte)0);
        sizePolicy1.setHeightForWidth(comboFontSizes.sizePolicy().hasHeightForWidth());
        comboFontSizes.setSizePolicy(sizePolicy1);
        comboFontSizes.setMaximumSize(new QSize(40, 16777215));

        horizontalLayout.addWidget(comboFontSizes);

        comboFontColors = new QComboBox(centralwidget);
        comboFontColors.setObjectName("comboFontColors");
        QSizePolicy sizePolicy2 = new QSizePolicy(com.trolltech.qt.gui.QSizePolicy.Policy.Fixed, com.trolltech.qt.gui.QSizePolicy.Policy.Fixed);
        sizePolicy2.setHorizontalStretch((byte)0);
        sizePolicy2.setVerticalStretch((byte)0);
        sizePolicy2.setHeightForWidth(comboFontColors.sizePolicy().hasHeightForWidth());
        comboFontColors.setSizePolicy(sizePolicy2);
        comboFontColors.setMaximumSize(new QSize(40, 16777215));

        horizontalLayout.addWidget(comboFontColors);

        MainWindow.setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar.setObjectName("menubar");
        menubar.setGeometry(new QRect(0, 0, 682, 21));
        menuFile = new QMenu(menubar);
        menuFile.setObjectName("menuFile");
        menuEdit = new QMenu(menubar);
        menuEdit.setObjectName("menuEdit");
        menuFormat = new QMenu(menubar);
        menuFormat.setObjectName("menuFormat");
        menuJustify = new QMenu(menuFormat);
        menuJustify.setObjectName("menuJustify");
        menuList_Style = new QMenu(menuFormat);
        menuList_Style.setObjectName("menuList_Style");
        menuHelp = new QMenu(menubar);
        menuHelp.setObjectName("menuHelp");
        menuView = new QMenu(menubar);
        menuView.setObjectName("menuView");
        MainWindow.setMenuBar(menubar);
        toolBar = new QToolBar(MainWindow);
        toolBar.setObjectName("toolBar");
        MainWindow.addToolBar(com.trolltech.qt.core.Qt.ToolBarArea.TopToolBarArea, toolBar);

        menubar.addAction(menuFile.menuAction());
        menubar.addAction(menuEdit.menuAction());
        menubar.addAction(menuFormat.menuAction());
        menubar.addAction(menuView.menuAction());
        menubar.addAction(menuHelp.menuAction());
        menuFile.addAction(actionNew_Note);
        menuFile.addAction(actionSave_Note);
        menuFile.addAction(actionDelete_Note);
        menuFile.addSeparator();
        menuFile.addAction(actionNew_Category);
        menuFile.addAction(actionDelete_Category);
        menuFile.addSeparator();
        menuFile.addAction(actionPrint_Note);
        menuFile.addAction(actionImport_Category);
        menuFile.addAction(actionExport_Category);
        menuFile.addSeparator();
        menuFile.addAction(actionQuit);
        menuEdit.addAction(actionUndo);
        menuEdit.addAction(actionRedo);
        menuEdit.addSeparator();
        menuEdit.addAction(actionCut);
        menuEdit.addAction(actionCopy);
        menuEdit.addAction(actionPaste);
        menuFormat.addAction(actionBold);
        menuFormat.addAction(actionItalic);
        menuFormat.addAction(actionUnderline);
        menuFormat.addAction(actionStrikethrough);
        menuFormat.addSeparator();
        menuFormat.addAction(menuJustify.menuAction());
        menuFormat.addSeparator();
        menuFormat.addAction(menuList_Style.menuAction());
        menuFormat.addAction(actionIncrease_Indent);
        menuFormat.addAction(actionDecrease_Indent);
        menuFormat.addSeparator();
        menuFormat.addAction(actionShow_Fonts);
        menuFormat.addAction(actionShow_Colors);
        menuFormat.addSeparator();
        menuFormat.addAction(actionIncrease_Font);
        menuFormat.addAction(actionDecrease_Font);
        menuFormat.addAction(actionReset_Font);
        menuJustify.addAction(actionLeft);
        menuJustify.addAction(actionCenter);
        menuJustify.addAction(actionRight);
        menuJustify.addAction(actionFull);
        menuList_Style.addAction(actionBullet_List);
        menuList_Style.addAction(actionNumeric_List);
        menuHelp.addAction(actionAbout_Brainstorm);
        menuHelp.addAction(actionAbout_QtJambi);
        menuView.addAction(actionNext_Category);
        menuView.addAction(actionPrevious_Category);
        menuView.addSeparator();
        menuView.addAction(actionNext_Note);
        menuView.addAction(actionPrevious_Note);
        toolBar.addAction(actionNew_Category);
        toolBar.addAction(actionNew_Note);
        toolBar.addAction(actionSave_Note);
        toolBar.addSeparator();
        toolBar.addAction(actionCut);
        toolBar.addAction(actionCopy);
        toolBar.addAction(actionPaste);
        toolBar.addSeparator();
        toolBar.addAction(actionBold);
        toolBar.addAction(actionItalic);
        toolBar.addAction(actionUnderline);
        toolBar.addAction(actionStrikethrough);
        toolBar.addSeparator();
        toolBar.addAction(actionBullet_List);
        toolBar.addAction(actionNumeric_List);
        toolBar.addAction(actionDecrease_Indent);
        toolBar.addAction(actionIncrease_Indent);
        toolBar.addSeparator();
        retranslateUi(MainWindow);

        MainWindow.connectSlotsByName();
    } // setupUi

    void retranslateUi(QMainWindow MainWindow)
    {
        MainWindow.setWindowTitle(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Brainstorm", null));
        actionQuit.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Quit", null));
        actionQuit.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+Q", null));
        actionNew_Note.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "New Note", null));
        actionNew_Note.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+N", null));
        actionRename_Note.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Rename Note", null));
        actionDelete_Note.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Delete Note", null));
        actionNew_Category.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "New Category", null));
        actionNew_Category.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+Shift+N", null));
        actionRename_Category.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Rename Category", null));
        actionDelete_Category.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Delete Category", null));
        actionImport_Category.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Import Category", null));
        actionExport_Category.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Export Category", null));
        actionUndo.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Undo", null));
        actionUndo.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+Z", null));
        actionRedo.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Redo", null));
        actionRedo.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+Y", null));
        actionCut.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Cut", null));
        actionCut.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+X", null));
        actionCopy.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Copy", null));
        actionCopy.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+C", null));
        actionPaste.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Paste", null));
        actionPaste.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+V", null));
        actionAbout_Brainstorm.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "About Brainstorm", null));
        actionAbout_QtJambi.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "About QtJambi", null));
        actionBold.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Bold", null));
        actionBold.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+B", null));
        actionItalic.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Italic", null));
        actionItalic.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+I", null));
        actionUnderline.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Underline", null));
        actionUnderline.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+U", null));
        actionStrikethrough.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Strikethrough", null));
        actionStrikethrough.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+K", null));
        actionLeft.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Left", null));
        actionCenter.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Center", null));
        actionRight.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Right", null));
        actionFull.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Full", null));
        actionShow_Fonts.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Show Fonts", null));
        actionShow_Fonts.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+T", null));
        actionShow_Colors.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Show Colors", null));
        actionIncrease_Font.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Increase Font", null));
        actionIncrease_Font.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+=", null));
        actionDecrease_Font.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Decrease Font", null));
        actionDecrease_Font.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+-", null));
        actionReset_Font.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Reset Font", null));
        actionPrint_Note.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Print Note...", null));
        actionPrint_Note.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+P", null));
        actionIncrease_Indent.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Increase Indent", null));
        actionDecrease_Indent.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Decrease Indent", null));
        actionBullet_List.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Bullet List", null));
        actionNumeric_List.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Numeric List", null));
        actionNext_Note.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Next Note", null));
        actionNext_Note.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Alt+Down", null));
        actionPrevious_Note.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Previous Note", null));
        actionPrevious_Note.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Alt+Up", null));
        actionNext_Category.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Next Category", null));
        actionNext_Category.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Alt+Shift+Down", null));
        actionPrevious_Category.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Previous Category", null));
        actionPrevious_Category.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Alt+Shift+Up", null));
        actionSave_Note.setText(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Save Note", null));
        actionSave_Note.setShortcut(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Ctrl+S", null));
        comboFontSizes.clear();
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "6", null));
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "7", null));
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "8", null));
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "9", null));
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "10", null));
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "11", null));
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "12", null));
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "13", null));
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "14", null));
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "16", null));
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "18", null));
        comboFontSizes.addItem(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "20", null));
        menuFile.setTitle(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "File", null));
        menuEdit.setTitle(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Edit", null));
        menuFormat.setTitle(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Format", null));
        menuJustify.setTitle(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Justify", null));
        menuList_Style.setTitle(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "List Style", null));
        menuHelp.setTitle(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "Help", null));
        menuView.setTitle(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "View", null));
        toolBar.setWindowTitle(com.trolltech.qt.core.QCoreApplication.translate("MainWindow", "toolBar", null));
    } // retranslateUi

}

